### ISSUE TITLE
Use Server-side Authentication

### ISSUE THREAD

**Issue by cybardev** [cybardev/pictionary#6]
## Issue

Currently, the authentication for admin view is done client-side. This is undesirable, as malicious actors could use the browsers' inbuilt "Inspect" functionality to view the password and add words recordings.

## Proposed Solution

Ideally, the typed passphrase would be sent to the server, where a server-side script or function could authenticate it and return a status code (pass/fail the authentication request). The client may then display a tooltip informing the user of a failed authentication, or move on to the next course of action.

---

## Tasks

- [x] create `GET` endpoint on server-side script for admin password
- [x] send password (in a secure way) to the server in client-side script
- [x] authenticate password on the server and send back status code
- [x] appropriately handle status code on client-side

**Comment by cybardev** [comment]
Attempted fix: e0ad5e706e58275bc4feabb956441d04aec58017

Needs testing.
