### ISSUE TITLE
Create Admin Endpoint

### ISSUE THREAD

**Issue by cybardev** [cybardev/pictionary#7]
## Issue

Currently, the admin view is invoked by clicking a button. This is undesirable, as it:
- can be clicked by kids
- can make the game UI cluttered

## Proposed solution

Remove the admin view button and have it as a separate webpage.

---

## Tasks

- [ ] make a separate webpage (`/admin/index.html`)
- [ ] validate admin with passphrase (server-side, see #6)
- [ ] connect requests to admin-accessible endpoints (edit [`server/server.js`](https://github.com/cybardev/pictionary/blob/main/src/server/server.js))
